EXTRAMODULES='extramodules-3.15.5-CHAKRA'

post_install() {
  systemd-tmpfiles --create lirc.conf
  echo ">>> Updating module dependencies. Please wait ..."
  depmod $(cat /lib/modules/$EXTRAMODULES/version) > /dev/null 2>&1
}

post_upgrade() {
  post_install
}

post_remove() {
  echo ">>> Updating module dependencies. Please wait ..."
  depmod $(cat /lib/modules/$EXTRAMODULES/version) > /dev/null 2>&1
}

