kerver="$(pacman -Q linux | awk '{print $2}' | cut -d - -f1 | cut -d . -f1,2)"
EXTRAMODULES="extramodules-${kerver}-CHAKRA"

post_install() {
  systemd-tmpfiles --create lirc.conf
  echo ">>> Updating module dependencies. Please wait ..."
  depmod $(cat /lib/modules/$EXTRAMODULES/version) > /dev/null 2>&1
}

post_upgrade() {
  post_install
}

post_remove() {
  echo ">>> Updating module dependencies. Please wait ..."
  depmod $(cat /lib/modules/$EXTRAMODULES/version) > /dev/null 2>&1
}

