post_install() {
  getent group nm-openvpn >/dev/null 2>&1 || groupadd -g 105 nm-openvpn
  getent passwd nm-openvpn > /dev/null 2>&1 || useradd -u 105 -s /sbin/nologin -d / -M -c 'NetworkManager user for OpenVPN' -g nm-openvpn nm-openvpn
  passwd -l nm-openvpn > /dev/null
}

post_upgrade() {
  post_install
}

post_remove() {
  getent passwd nm-openvpn >/dev/null 2>&1 && userdel nm-openvpn
  getent group nm-openvpn >/dev/null 2>&1 && groupdel nm-openvpn
}
