--- /etc/Makefile.am	2013-07-20 21:51:37.675986920 +0000
+++ /etc/Makefile.am	2013-07-20 21:51:58.399208143 +0000
@@ -4,7 +4,7 @@
 
 #make sure the slpd log directory is there
 install-data-hook:
-	mkdir -p $(localstatedir)/log
+	mkdir -p $(DESTDIR)$(localstatedir)/log
 
 ##install-data-local:
 ##	mkdir -p $(DESTDIR)$(sysconfdir)
