post_install() {
  echo "sna and uxa acceleration methods are now supported"
  echo "Add to the device section in /etc/X11/xorg.conf.d/20-intel.conf"
  echo "Section "Device""
  echo "    Identifier "Intel Graphics""
  echo "    Driver "intel""
  echo "    Option "Accelmethod" "sna""
  echo "EndSection"
  echo "Use the uxa method if you run into trouble with sna."
}

post_upgrade() {
  post_install
}
  