## arg 1:  the new package version
post_install() {
cat << 'EOM'
  ==> PLEASE NOTE:
  ==> Extended configuration options for NFS (clients & server) are available in
  ==> /etc/conf.d/nfs-common.conf and in /etc/conf.d/nfs-server.conf
  ==>
  ==> We suggest to refer the Arch wiki http://wiki.archlinux.org/index.php/NFS
  ==> for further information on NFS4; for NFSv3, refer to
  ==> http://wiki.archlinux.org/index.php/NFSv3   
EOM
}

