post_install() {
  echo -n "Updating font cache... "
  fc-cache -f > /dev/null
  mkfontscale /usr/share/fonts/TTF
  mkfontdir /usr/share/fonts/TTF
  echo "done."
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  [[ -e /usr/share/fonts/TTF/msfonts.txt ]] && \
  for i in `cat /usr/share/fonts/TTF/msfonts.txt`; do
    rm -f /usr/share/fonts/TTF/$i
  done
  rm -f /usr/share/fonts/TTF/msfonts.txt
}

post_remove() {
  post_install
}
